server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Redireciona chamadas /api para o backend
    location /api/ {
        proxy_pass http://caltech-backend:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA — todas as rotas caem no index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
